-- DROP DATABASE IF EXISTS garage;
CREATE DATABASE IF NOT EXISTS garage;

USE garage;

CREATE TABLE IF NOT EXISTS brands (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS cars;
CREATE TABLE IF NOT EXISTS voitures (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    model VARCHAR(255) NOT NULL,
    build_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    price INT NOT NULL,
    brand_id INT NOT NULL,
    -- PRIMARY KEY(id)
    FOREIGN KEY (brand_id) REFERENCES brands(id)
);

ALTER TABLE voitures RENAME cars;

ALTER TABLE cars
ADD color VARCHAR(255);

ALTER TABLE cars
MODIFY color VARCHAR(100);

CREATE TABLE movie_copy SELECT id FROM movies.movie WHERE category_id = 1;
